pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/BenjaminMoya/tingeso-ev1']])
                dir("CreditAdministrationUI"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("CreditAdministrationUI"){
                    withCredentials([usernamePassword(credentialsId: 'credentialsId', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "docker login -u $USER -p $PASS"
                        sh "docker build --no-cache -t benjaminmoya/creditapp-frontend:latest ."
                        sh "docker push benjaminmoya/creditapp-frontend:latest"
                    }
                }
            }
        }
    }
}